ui/hooks: alert detail page
target/goalert pull request #1001
Opened 2020-11-05 21:24 UTC by dctalbot

- [x] Identified the issue which this PR solves.
- [x] Read the [**CONTRIBUTING**](https://github.com/target/goalert/blob/master/CONTRIBUTING.md) document.
- [x] Code builds clean without any errors or warnings.
- [x] Added appropriate tests for any new functionality.
- [x] All new and existing tests passed.
- [x] Added comments in the code, where necessary.
- [x] Ran `make check` to catch common errors. Fixed any that came up.

**Description:**
This PR has AlertDetailPage using hooks

**Which issue(s) this PR fixes:**
Part of #923

2020-11-05 22:16 UTC, mastercactapus requested changes

2020-11-05 22:16 UTC, mastercactapus commented on web/src/app/alerts/pages/AlertDetailPage.js
> +    pollInterval: POLL_INTERVAL,
I think this and `startPolling` can be removed now that we're using `useQuery` it should be the default now

2020-11-06 17:32 UTC, mastercactapus approved these changes

2020-11-09 19:39 UTC, KatieMSB approved these changes

2020-11-09 19:55 UTC, merged