fix: resolve console error for invalid ref forwarding
target/goalert pull request #1002
Opened 2020-11-05 21:55 UTC by dctalbot

- [x] Identified the issue which this PR solves.
- [ ] Read the [**CONTRIBUTING**](https://github.com/target/goalert/blob/master/CONTRIBUTING.md) document.
- [ ] Code builds clean without any errors or warnings.
- [ ] Added appropriate tests for any new functionality.
- [ ] All new and existing tests passed.
- [ ] Added comments in the code, where necessary.
- [ ] Ran `make check` to catch common errors. Fixed any that came up.

**Description:**
This PR resolves an issue introduced when AppLink list items were wrapped with `li` tags, composed as functional components. You can read more [here](https://material-ui.com/guides/composition/#caveat-with-refs) if you're interested in why this is an issue.

2020-11-05 22:26 UTC, mastercactapus requested changes

2020-11-05 22:26 UTC, mastercactapus commented on web/src/app/lists/PaginatedList.tsx
> +            <AppLink {...props}>{children}</AppLink>
Doesn't `ref` need to be passed to AppLink (which has `forwardRef` internally) to pass it to `Link`?

2020-11-11 17:49 UTC, mastercactapus approved these changes

2020-11-16 17:19 UTC, KatieMSB approved these changes

2020-11-16 17:45 UTC, merged