ui/hooks: policy services query
target/goalert pull request #1023
Opened 2020-11-12 16:54 UTC by KatieMSB

- [x] Identified the issue which this PR solves.
- [x] Read the [**CONTRIBUTING**](https://github.com/target/goalert/blob/master/CONTRIBUTING.md) document.
- [x] Code builds clean without any errors or warnings.
- [x] Added appropriate tests for any new functionality.
- [x] All new and existing tests passed.
- [x] Added comments in the code, where necessary.
- [x] Ran `make check` to catch common errors. Fixed any that came up.

**Description:**
Please include a description of the proposed changes.
Converts PolicyServicesQuery.js to use hooks.

**Which issue(s) this PR fixes:**
Part of #923

2020-11-12 17:44 UTC, mastercactapus requested changes
Agree with @dctalbot let's use the hooks version for the apollo query

2020-11-12 21:10 UTC, Forfold approved these changes

2020-11-13 00:07 UTC, mastercactapus requested changes

2020-11-13 00:07 UTC, mastercactapus commented on web/src/app/escalation-policies/PolicyServicesQuery.js
> +  if (error) {
We'll also need a check like: `if (!data.escalationPolicy) return <ObjectNotFound />` otherwise it will throw an error for a missing policy.

2020-11-13 17:02 UTC, mastercactapus approved these changes

2020-11-13 17:02 UTC, merged