replace lodash-es with lodash
target/goalert pull request #1035
Opened 2020-11-17 20:27 UTC by dctalbot

- [x] Identified the issue which this PR solves.
- [x] Read the [**CONTRIBUTING**](https://github.com/target/goalert/blob/master/CONTRIBUTING.md) document.
- [x] Code builds clean without any errors or warnings.
- [x] Added appropriate tests for any new functionality.
- [x] All new and existing tests passed.
- [x] Added comments in the code, where necessary.
- [x] Ran `make check` to catch common errors. Fixed any that came up.

**Description:**
Fixes #101

2020-11-17 21:15 UTC, mastercactapus submitted a review, later dismissed

2020-11-17 22:27 UTC, KatieMSB requested changes

2020-11-17 22:27 UTC, KatieMSB commented on web/src/webpack.dll.config.js
> +      'lodash',
`lodash` is included in the vendorPackages lower down in the list so `lodash-es` should jut be removed.

2020-11-18 15:23 UTC, KatieMSB approved these changes

2020-11-18 16:07 UTC, mastercactapus approved these changes

2020-11-18 16:08 UTC, merged