mobile: initialize with expo
target/goalert pull request #1037
Opened 2020-11-17 21:09 UTC by Forfold

- [x] Identified the issue which this PR solves.
- [x] Read the [**CONTRIBUTING**](https://github.com/target/goalert/blob/master/CONTRIBUTING.md) document.
- [ ] Code builds clean without any errors or warnings.
- [ ] Added appropriate tests for any new functionality.
- [ ] All new and existing tests passed.
- [x] Added comments in the code, where necessary.
- [ ] Ran `make check` to catch common errors. Fixed any that came up.

**Description:**
This PR introduces the folder `/mobile` at root which holds the start of GoAlert's mobile application, built in React Native using Expo. I've included a home and a settings screen utilizing `react-navigation`.

Run `yarn start` from within this directory to spin up the mobile app.

**Screenshots:**
<img width="350" src="https://user-images.githubusercontent.com/11381794/99450397-92255f80-28d5-11eb-991b-e08840978865.png" />

2020-11-17 21:23 UTC, Forfold commented
I haven't heard of yarn workspaces before, so I'll check it out!

2020-11-25 21:59 UTC, Forfold commented
Good catch, the lockfile must have slipped through the cracks from the reverts. I'll be sure to remove it and make sure `web` is in a clean state 👍

2020-11-30 07:05 UTC, mastercactapus requested changes
Can we get this integrated with the Makefile?

Something like `make start MOBILE=1`? That should handle running `yarn` in the mobile directory (frozen lockfile) just like we do with the web UI, starting the backend, etc...

Also, it looks like `expo-cli` is missing as a required dependency for that to work properly -- we'll want to track it in package.json so we're not dealing with version mismatch issues, have to document/explain how to install it, dangers of using npm with sudo, etc...

Ideally, as long as docker/node/Go is installed, `make start MOBILE=1` should result in all necessary dependencies being installed and expo starting, the backend, and the web UI. We could have a separate start command, but I think in most cases (at least to start) you'll still need/want the web interface in addition to mobile for things like linking/login.

Lastly, I forget where we landed, but should this be going into a feature branch until we have the MVP working (login + alerts)?

2020-11-30 07:13 UTC, mastercactapus commented
Also, I tried playing with workspaces locally, seems to really speed things up, and would probably go a long way to simplify dep handling /w the Makefile

2020-12-01 22:43 UTC, Forfold commented
I'm also a fan of all of the above (`Makefile` additions, `expo-cli` tracking, and using a feature branch) 👍

Since we want to hold off on merging into master, how does adding those enhancements as follow-up issues/PRs sound so we can start to divvy up the work? I'll get a feature branch started and update the base of this PR

2021-07-06 20:40 UTC, mastercactapus commented
Closing due to age; will do a new spike when we cycle back to mobile.

2021-07-06 20:40 UTC, closed without merging