ui/escalation-policies: use NumberField for delay minutes
target/goalert pull request #1097
Opened 2020-12-07 21:49 UTC by dctalbot

- [x] Identified the issue which this PR solves.
- [x] Read the [**CONTRIBUTING**](https://github.com/target/goalert/blob/master/CONTRIBUTING.md) document.
- [x] Code builds clean without any errors or warnings.
- [x] Added appropriate tests for any new functionality.
- [x] All new and existing tests passed.
- [x] Added comments in the code, where necessary.
- [x] Ran `make check` to catch common errors. Fixed any that came up.

**Description:**
This PR has the delay minutes form field use the `NumberField` component making it unclearable, preventing invalid hint text.

**Which issue(s) this PR fixes:**
Fixes #1055

**Describe any introduced user-facing changes:**
Users can't clear the field since it is required.

2020-12-09 17:01 UTC, mastercactapus submitted a review, later dismissed

2020-12-15 19:41 UTC, Forfold requested changes

2020-12-15 19:41 UTC, Forfold commented on web/src/app/escalation-policies/PolicyStepForm.js
>              label='Delay (minutes)'
We should be able to remove `type` and `mapOnChangeValue` now, as they are handled within `NumberField`

2020-12-15 20:08 UTC, Forfold approved these changes

2020-12-15 20:22 UTC, Forfold approved these changes

2020-12-15 21:37 UTC, arurao approved these changes

2020-12-15 21:38 UTC, merged