alerts smtp: add config validation
target/goalert pull request #1189
Opened 2021-01-14 20:26 UTC by arurao

- [x] Identified the issue which this PR solves.
- [x] Read the [**CONTRIBUTING**](https://github.com/target/goalert/blob/master/CONTRIBUTING.md) document.
- [x] Code builds clean without any errors or warnings.
- [x] Added appropriate tests for any new functionality.
- [x] All new and existing tests passed.
- [x] Added comments in the code, where necessary.
- [x] Ran `make check` to catch common errors. Fixed any that came up.

**Description:**
This PR adds validation for the config changes for smtp, when enabled. 
Validating that the `from` email address is a valid email and `SMTP` when enabled, makes sure that `from` is also specified.

2021-01-14 20:59 UTC, mastercactapus requested changes
We also need to validate that `Address` is set on

2021-01-14 20:59 UTC, mastercactapus commented on config/config.go
> +		),
Also need address to connect to set:
```suggestion
			"From", cfg.SMTP.From,
			"Address", cfg.SMTP.Address,
		),
```

2021-01-16 16:38 UTC, mastercactapus approved these changes

2021-01-18 15:50 UTC, KatieMSB approved these changes

2021-01-18 15:57 UTC, merged