ui/schedules: hide time zone switch for schedules configured in local time zone
target/goalert pull request #1206
Opened 2021-01-22 15:18 UTC by dctalbot

- [x] Identified the issue which this PR solves.
- [x] Read the [**CONTRIBUTING**](https://github.com/target/goalert/blob/master/CONTRIBUTING.md) document.
- [x] Code builds clean without any errors or warnings.
- [x] Added appropriate tests for any new functionality.
- [ ] All new and existing tests passed.
- [x] Added comments in the code, where necessary.
- [x] Ran `make check` to catch common errors. Fixed any that came up.

**Description:**
- `ScheduleTZFilter` converted to typescript
- custom labels using `label` prop
- optional `render` prop allows for wrapping switch element output
- hidden when system time zone === schedule's time zone
- modified column widths on the schedule override form to prevent default text from having an orphaned word

**Which issue(s) this PR fixes:**
fixes #1067

**Describe any introduced user-facing changes:**
Users will not be able to toggle time zones for schedules configured in the local zone (current behavior is effectively a no-op).

2021-01-25 17:48 UTC, Forfold requested changes

2021-01-25 17:48 UTC, Forfold commented on web/src/app/schedules/ScheduleRuleList.js
> +              <FilterContainer onReset={() => this.props.resetFilter()}>
What's going on here makes sense, but having the Wrapper/Container element nested in the Filter as a prop reads a little off. What is the main benefit in reversing the children logic here into a render prop?

2021-01-25 18:59 UTC, Forfold commented
Looks like we'll need to be watching if the timezone changes, if you change the timezone to your local zone (with the toggle currently set to true) and then re-open a form with the filter, it appears to get out of sync. I'm noticing this behavior in prod, too, though it can be resolved there by clicking the toggle twice

<img width="870" alt="Screen Shot 2021-01-25 at 10 54 21 AM" src="https://user-images.githubusercontent.com/11381794/105752076-b4ea7a80-5efb-11eb-8b25-efae86835b2f.png">

2021-01-25 20:15 UTC, Forfold commented
I don't think we can reset the TZ filter on dialog close since we purposefully save that info in the URL so it stays consistent while viewing shifts/the calendar/etc. The TZ can also change while other people are working on the schedule, too.

We could likely poll for the timezone on the schedule/track TZ changes from the URL, and make the appropriate changes when either gets out of sync

2021-01-26 15:28 UTC, Forfold commented
We do intentionally leave the timezone in the URL for the whole schedule. I can see how not having it available as a filter from the main detail does make it awkward. Ultimately I feel a proper solution that I've mentioned a few times in the past would be a global setting for a user to choose which timezone to view anything in GoAlert in

2021-01-26 15:49 UTC, mastercactapus commented
I think this work may need to go through additional discussion first.

The current implementation (using the URL param) was intentional to ensure timestamp-in-timezone rendering is always consistent for the entire page (no possibility of mix/match) and persists in a refresh. It was also meant to be on the details page but the calendar lacks support so it's stuck local-only.

---

We should focus on: what problem are users facing today that we are trying to solve, and what would the ideal experience/solution be.

We can discuss other ideas as well that way, maybe a switch from one to the other isn't even the best approach in the first place. Then we can talk about what changes need to be made to achieve that without spinning during the review.

2021-01-26 18:26 UTC, Forfold commented on web/src/app/schedules/ScheduleTZFilter.tsx
>      pollInterval: 0,
I think if we were to remove this line we would get the logic desired to fix the current bug + move forward with this PR

2021-01-26 18:48 UTC, Forfold commented on web/src/app/schedules/ScheduleTZFilter.tsx
>      pollInterval: 0,
Needs a slight bit more ^, but it's working so far with using an Effect as well to watch for changes:

```suggestion
  const [filterTZ, setFilterTZ] = useURLParam('tz', 'local')
  const resetTZ = useResetURLParams('tz')
  const { data, loading, error } = useQuery(tzQuery, {
    variables: { id: props.scheduleID },
  })
  const scheduleTZ = data?.schedule?.timeZone
  const localTZ = DateTime.local().zone.name

  useEffect(() => {
    if (filterTZ === localTZ || localTZ === scheduleTZ) {
      resetTZ()
    }
  }, [scheduleTZ])

  if (localTZ === scheduleTZ) return null
```

2021-02-01 22:19 UTC, closed without merging