ui/schedules: refactor calendar toolbar
target/goalert pull request #1435
Opened 2021-04-20 21:01 UTC by dctalbot

- [x] Identified the issue which this PR solves.
- [x] Read the [**CONTRIBUTING**](https://github.com/target/goalert/blob/master/CONTRIBUTING.md) document.
- [x] Code builds clean without any errors or warnings.
- [x] Added appropriate tests for any new functionality.
- [x] All new and existing tests passed.
- [x] Added comments in the code, where necessary.
- [x] Ran `make check` to catch common errors. Fixed any that came up.

**Description:**
There were a few code smells here that I ironed out
- mixed use of `week=1` URL param with `props.view === 'week'`
- passing certain props through unnecessarily which can impact perf, especially important on the schedule page
- pulled references to temporary schedules out of the toolbar in favor of a generic "action button" 

**Describe any introduced user-facing changes:**
N/A

2021-04-23 21:17 UTC, Forfold requested changes

2021-04-23 21:17 UTC, Forfold commented on web/src/app/schedules/CalendarToolbar.tsx
> +            }}
I'd prefer to keep the action handlers/logic-y bits out of the JSX portion of the component

2021-04-26 17:00 UTC, Forfold approved these changes
lgtm

2021-04-26 19:27 UTC, pnengchu approved these changes

2021-04-26 19:27 UTC, merged