Refactored OtherActionsMenuMobile class component to a functional com…
target/goalert pull request #1716
Opened 2021-07-09 08:11 UTC by Voninkazo

- [x] Identified the issue which this PR solves.
- [ ] Read the [**CONTRIBUTING**](https://github.com/target/goalert/blob/master/CONTRIBUTING.md) document.
- [ ] Code builds clean without any errors or warnings.
- [ ] Added appropriate tests for any new functionality.
- [ ] All new and existing tests passed.
- [ ] Added comments in the code, where necessary.
- [ ] Ran `make check` to catch common errors. Fixed any that came up.

**Description:**
Refactoring the OtherActionsMenuMobile class component to functional component.
You can find the branch in this [link](https://github.com/Voninkazo/goalert/tree/other-actions-menu-mobile)

Usage: `Fixes #<issuOtherActionsMenuDesktop >`

2021-07-09 16:37 UTC, Forfold requested changes
Looks good! Just 1 comment about a proptype that's no longer used and then it should be good to go 👍

2021-07-09 16:37 UTC, Forfold commented on web/src/app/util/OtherActionsMobile.js
> +  anchorEl: p.object,
It doesn't look like this prop is used, so lets delete this line
```suggestion
```

2021-07-12 13:26 UTC, mastercactapus requested changes

2021-07-13 16:10 UTC, Forfold approved these changes

2021-07-13 16:15 UTC, mastercactapus approved these changes

2021-07-14 15:40 UTC, merged