Schedule override delete dialog
target/goalert pull request #1725
Opened 2021-07-12 05:45 UTC by Voninkazo

- [x] Identified the issue which this PR solves.
- [ ] Read the [**CONTRIBUTING**](https://github.com/target/goalert/blob/master/CONTRIBUTING.md) document.
- [ ] Code builds clean without any errors or warnings.
- [ ] Added appropriate tests for any new functionality.
- [ ] All new and existing tests passed.
- [ ] Added comments in the code, where necessary.
- [ ] Ran `make check` to catch common errors. Fixed any that came up.

**Description:**
Refactoring the Schedule override delete dialog class component to a functional component.

2021-07-12 13:30 UTC, mastercactapus requested changes

2021-07-12 13:30 UTC, mastercactapus commented on web/src/app/schedules/ScheduleOverrideDeleteDialog.js
>  @connect((state) => ({ zone: urlParamSelector(state)('tz') }))
Switch decorators to use hooks

2021-07-12 13:30 UTC, mastercactapus commented on web/src/app/schedules/ScheduleOverrideDeleteDialog.js
> +  proScheduleOverrideDeleteDialogps
not sure what this is

2021-07-15 20:53 UTC, Forfold approved these changes

2021-07-15 20:54 UTC, merged