ui/hooks: ServiceLabelEditDialog
target/goalert pull request #1750
Opened 2021-07-14 08:13 UTC by voromahery

- [x] Identified the issue which this PR solves.
- [x] Read the [**CONTRIBUTING**](https://github.com/target/goalert/blob/master/CONTRIBUTING.md) document.
- [x] Code builds clean without any errors or warnings.
- [x] Added appropriate tests for any new functionality.
- [x] All new and existing tests passed.
- [x] Added comments in the code, where necessary.
- [x] Ran `make check` to catch common errors. Fixed any that came up.

**Description:**
Converts this file into hooks

**Which issue(s) this PR fixes:**
Part of #923

2021-07-16 18:08 UTC, Forfold requested changes

2021-07-16 18:08 UTC, Forfold commented on web/src/app/services/ServiceLabelEditDialog.js
> +  const { onClose, labelKey, serviceID } = props
nit, swap these two lines to keep prop destructering at the top:
```suggestion
  const { onClose, labelKey, serviceID } = props
  const [value, setValue] = useState(null)
```

2021-07-16 18:08 UTC, Forfold commented on web/src/app/services/ServiceLabelEditDialog.js
> +            variables: { serviceID: serviceID },
since the names are the same, in Javascript you can reference `serviceID` once:
```suggestion
            variables: { serviceID },
```

2021-07-16 18:08 UTC, Forfold commented on web/src/app/services/ServiceLabelEditDialog.js
> +        variables={{ serviceID: serviceID }}
```suggestion
        variables={{ serviceID }}
```

2021-07-19 18:22 UTC, KatieMSB submitted a review, later dismissed

2021-07-20 21:42 UTC, Forfold requested changes
<img width="1064" alt="Screen Shot 2021-07-20 at 2 41 18 PM" src="https://user-images.githubusercontent.com/11381794/126399227-d98c38c0-4c4a-4f7f-b375-e0b00d040030.png">

2021-07-20 21:42 UTC, Forfold commented on web/src/app/services/ServiceLabelEditDialog.js
> +            onChange={(value) => setValue({ value })}
```suggestion
            onChange={(value) => setValue(value)}
```

2021-07-22 20:17 UTC, KatieMSB requested changes

2021-07-22 20:17 UTC, KatieMSB commented on web/src/app/services/ServiceLabelEditDialog.js
> +ServiceLabelCreateDialog.propTypes = {
```suggestion
ServiceLabelEditDialog.propTypes = {
```

2021-07-22 20:17 UTC, KatieMSB commented on web/src/app/services/ServiceLabelEditDialog.js
> +export default function ServiceLabelCreateDialog(props) {
```suggestion
export default function ServiceLabelEditDialog(props) {
```

2021-07-26 19:53 UTC, KatieMSB approved these changes

2021-08-04 16:41 UTC, Forfold approved these changes

2021-08-04 17:04 UTC, merged