On call cleanup
target/goalert pull request #2054
Opened 2021-12-09 16:50 UTC by dctalbot

- [x] Identified the issue which this PR solves.
- [x] Read the [**CONTRIBUTING**](https://github.com/target/goalert/blob/master/CONTRIBUTING.md) document.
- [x] Code builds clean without any errors or warnings.
- [ ] Added appropriate tests for any new functionality.
- [x] All new and existing tests passed.
- [x] Added comments in the code, where necessary.
- [x] Ran `make check` to catch common errors. Fixed any that came up.

**Description:**
The PR introduces cleanup for 3 additional tables: `user_overrides` `schedule_on_call_users` and `ep_step_on_call_users`

**Which issue(s) this PR fixes:**
Fixes #916 

**Describe any introduced user-facing changes:**
In admin config panel, "Alert Cleanup days" has been renamed to "Data cleanup days", and the associated description has been updated appropriately.

**Describe any introduced API changes:**
Deprecated `'Maintenance.AlertCleanupDays'` in favor of `'Maintenance.DataCleanupDays'`

2021-12-09 17:32 UTC, mastercactapus requested changes

2021-12-09 17:32 UTC, mastercactapus commented on config/config.go
> +		DataCleanupDays  int `public:"true" info:"Various data records including alerts and on-call history will be deleted after this many days (0 means disable cleanup)."`
Can't change this since it's been in the wild and we need to preserve the intent, we'll need to add a new field and leave this one alone.

2021-12-15 15:49 UTC, mastercactapus approved these changes

2021-12-16 16:49 UTC, arurao approved these changes
lgtm

2021-12-16 17:01 UTC, merged