ui: refactor `useURLParam`
target/goalert pull request #2067
Opened 2021-12-22 17:27 UTC by dctalbot

- [x] Identified the issue which this PR solves.
- [x] Read the [**CONTRIBUTING**](https://github.com/target/goalert/blob/master/CONTRIBUTING.md) document.
- [x] Code builds clean without any errors or warnings.
- [x] Added appropriate tests for any new functionality.
- [x] All new and existing tests passed.
- [x] Added comments in the code, where necessary.
- [x] Ran `make check` to catch common errors. Fixed any that came up.

**Description:**
This PR continues our effort to reduce our dependency on redux for client side routing by:
- refactoring `useURLParam` to use the `react-router` API's directly
- writing unit tests for _getting_ a URL param and sanitizing param values pre-_setting_ them
- refactoring `useURLParam` to share logic in `setURL`, and to not clear all params by default if an empty list is passed (too much magic, unrealistic use case)

Bug fixes:
- `sanitizeParam` did not handle numeric zero values correctly, and it didn't trim string values when given a `string[]`
- a few usages of `useURLParam` were not passing in the required `defaultValue` argument

2021-12-28 20:15 UTC, pnengchu approved these changes

2021-12-29 16:28 UTC, mastercactapus requested changes

2021-12-29 16:28 UTC, mastercactapus commented on web/src/app/actions/hooks.ts
> +function setURL(
nit: can we call this `setParams` or similar?

Also, order the args by importance/change frequency: history, location, params
history is our fixed API for updating, we use location as a reference, and params is the real argument we're using to update the search string.

2021-12-29 16:28 UTC, mastercactapus commented on web/src/app/actions/hooks.ts
> +  const url = new URLSearchParams(location.search)
nit: should probably call this `params` here and elsewhere since it's not the full URL

2022-01-04 15:27 UTC, mastercactapus approved these changes

2022-01-05 16:08 UTC, mastercactapus approved these changes

2022-01-05 16:40 UTC, merged