Alert metrics dashboard
target/goalert pull request #2085
Opened 2022-01-06 17:16 UTC by dctalbot

- [x] Identified the issue which this PR solves.
- [x] Read the [**CONTRIBUTING**](https://github.com/target/goalert/blob/master/CONTRIBUTING.md) document.
- [x] Code builds clean without any errors or warnings.
- [ ] Added appropriate tests for any new functionality.
- [x] All new and existing tests passed.
- [x] Added comments in the code, where necessary.
- [x] Ran `make check` to catch common errors. Fixed any that came up.

**Description:**
This PR is the first iteration of the Alert Metrics dashboard feature. It provides:
- a graph of alert counts, grouped by date in the user's system timezone (shows 100 alerts max). 
- A date range filter to view the past 1, 2, 3, or 4 weeks of alerts.
- A service filter to view 1 or more services

**Screenshots:**
<img width="726" alt="Screen Shot 2022-01-06 at 11 15 28 AM" src="https://user-images.githubusercontent.com/17692467/148423047-cbeeb2ac-25f8-4354-a2ef-a1141bb50935.png">

2022-01-17 21:22 UTC, Forfold requested changes

2022-01-17 21:22 UTC, Forfold commented on web/src/app/selection/QuerySelect.js
> +  label: p.string,
Is this needed? It looks like it's not being used within the file since it's bunched in with the `otherProps` spread

2022-01-17 21:22 UTC, Forfold commented on web/src/app/services/AlertMetrics/AlertMetricsCSV.tsx
> +    [`createdAt (${zoneAbbr})`]: DateTime.fromISO(a.createdAt).toLocal().toSQL({
So this one is interesting, it shows the full value in when i click on a cell but just the `minutes:seconds.milliseconds` in the cell preview. Is there a way around that?

<img width="315" alt="Screen Shot 2022-01-17 at 11 38 37 AM" src="https://user-images.githubusercontent.com/11381794/149838036-792d9197-295a-4b0a-a8a6-8098ef1cbed6.png">

2022-01-18 20:40 UTC, Forfold approved these changes
LGTM! Loads well with a clean console  🎉  Functionally tested exporting a CSV of alerts as well.

2022-01-18 21:07 UTC, arurao approved these changes
LGTM. Functionally validated. Nice work!

2022-01-18 21:59 UTC, merged