Migrate playground to graphiql
target/goalert pull request #2210
Opened 2022-03-03 19:52 UTC by dctalbot

- [x] Identified the issue which this PR solves.
- [x] Read the [**CONTRIBUTING**](https://github.com/target/goalert/blob/master/CONTRIBUTING.md) document.
- [x] Code builds clean without any errors or warnings.
- [x] Added appropriate tests for any new functionality.
- [x] All new and existing tests passed.
- [x] Added comments in the code, where necessary.
- [x] Ran `make check` to catch common errors. Fixed any that came up.

**Description:**
This PR supersedes #2167 and closes #2160

By embedding an html asset, we remove the CDN dependency and avoid cypress test complexity

2022-03-07 21:05 UTC, mastercactapus requested changes
Not sure I like having `web/explore` and `graphql/explore` for the same purpose but different places.

Not 100% sure on how we should handle it though.

We *could* add it under `web/src/explore` (along side app) and add the handler code to the `web` package, though that might be mixing things a bit much since they are very different build processes.

We could move what's in `web/explore` to `graphql/explore/src` to mimick web, where the `explore` package is the Go handler code and `src` is the web/js stuff

WYT?

2022-03-07 21:05 UTC, mastercactapus commented on Makefile
> +EXPLORE_BUILD = $(shell find graphql2/explore/build)
This is only going to find files that exist, meaning it won't register targets until AFTER being built, since we know them we can add them directly.

2022-03-08 19:53 UTC, mastercactapus commented on app/inithttp.go
> +	}
We can check with the embed.FS https://pkg.go.dev/embed#hdr-File_Systems

2022-03-24 15:24 UTC, mastercactapus approved these changes

2022-04-01 15:35 UTC, mastercactapus commented on web/src/esbuild.config.js
> +      '.js': 'jsx',
No, it will handle `.tsx` and `.jsx` files by default -- but since we are using `jsx` inside `.js` files, we just need to specify that.

2022-04-01 16:40 UTC, Forfold approved these changes

2022-04-01 19:59 UTC, merged