ui/lists: use theme for highlighted items
target/goalert pull request #2238
Opened 2022-03-10 21:20 UTC by dctalbot

- [x] Identified the issue which this PR solves.
- [x] Read the [**CONTRIBUTING**](https://github.com/target/goalert/blob/master/CONTRIBUTING.md) document.
- [x] Code builds clean without any errors or warnings.
- [x] Added appropriate tests for any new functionality.
- [x] All new and existing tests passed.
- [x] Added comments in the code, where necessary.
- [x] Ran `make check` to catch common errors. Fixed any that came up.

**Description:**
This PR uses the theme for highlighted and being-dragged list items. We can use the `selected` prop for highlight, and I decided to go with the `theme.palette.background.default` for the being-dragged.

Components of interest are: 
- user session list
- rotation user list
- ep step list

**Which issue(s) this PR fixes:**
Part of #2214

**Screenshots:**
Before:
<img width="329" alt="Screen Shot 2022-03-10 at 3 20 16 PM" src="https://user-images.githubusercontent.com/17692467/157756674-a2f61247-090f-49f8-8c46-555398a84c78.png">

After:
<img width="607" alt="Screen Shot 2022-03-10 at 3 15 21 PM" src="https://user-images.githubusercontent.com/17692467/157756191-6cdb5710-729e-4b84-bed2-46dd7b581a22.png">

2022-03-14 16:36 UTC, Forfold requested changes
Highlighted items show slightly lighter than I'd hope they'd turn out in light mode with the color PR merged. I wonder if there's a way to use the same color as the highlighting used in the sidebar? It's just a bit darker. I also wonder if it would be beneficial to change the secondary item text from grey to something darker, or the same as the primary text for highlighted items

<img width="727" alt="Screen Shot 2022-03-14 at 9 32 40 AM" src="https://user-images.githubusercontent.com/11381794/158218046-da568fa6-ea8f-4945-a832-d94c559322c6.png">

2022-04-01 18:25 UTC, Forfold commented
this could be an opportunity to use the tertiary color from the m3 palette, since the primary and secondary are both somewhat similar

2022-04-19 18:21 UTC, mastercactapus approved these changes

2022-04-25 19:17 UTC, Forfold approved these changes
pulled this down to functionally test. I think the color we have set now will work because we have it against the white background of the cards

2022-04-25 21:02 UTC, merged