engine/metrics: populate closed_at field in alert_metrics
target/goalert pull request #2258
Opened 2022-03-21 20:24 UTC by dctalbot

- [x] Identified the issue which this PR solves.
- [x] Read the [**CONTRIBUTING**](https://github.com/target/goalert/blob/master/CONTRIBUTING.md) document.
- [x] Code builds clean without any errors or warnings.
- [x] Added appropriate tests for any new functionality.
- [x] All new and existing tests passed.
- [x] Added comments in the code, where necessary.
- [x] Ran `make check` to catch common errors. Fixed any that came up.

**Description:**
This PR populates a `closed_at` column in `alert_metrics` that will help with the implementation of #2122

2022-03-22 16:35 UTC, mastercactapus requested changes
Were we going to change this to do a sliding time window instead of going by alert ID?

2022-03-22 16:35 UTC, mastercactapus commented on engine/metricsmanager/update.go
> +	V2 struct {
The struct/meaning hasn't changed, no need to increment the version

2022-03-22 16:35 UTC, mastercactapus commented on migrate/migrations/20220317153438-alert-metrics-add-closed-at.sql
> +ALTER TABLE alert_metrics ADD COLUMN closed_at TIMESTAMP WITH TIME ZONE;
We should make this not-null and truncate the table so we recalculate existing data

2022-03-29 19:35 UTC, m17ch submitted a review, later dismissed
lgtm 👍

2022-03-29 20:01 UTC, m17ch approved these changes

2022-03-29 21:31 UTC, mastercactapus approved these changes

2022-03-29 21:48 UTC, merged