ui/: fix drag and drop in FlatList while in strict mode
target/goalert pull request #2413
Opened 2022-05-25 21:17 UTC by Forfold

This PR fixes part of #2412 the drag-and-drop functionality when in Strict Mode by replacing the current DND library we use (`react-beautiful-dnd`) with `react-dnd`, as `react-beautiful-dnd` is no longer being maintained.

out of scope:
- refactoring PolicyStepsCard to use FlatList for drag and drop
- removing `react-beautiful-dnd` and `@types/react-beautiful-dnd` packages afterwards

2022-06-16 21:09 UTC, tony-tvu approved these changes
Functionally tested :white_check_mark:

2022-06-29 20:09 UTC, tony-tvu approved these changes

2022-06-29 20:44 UTC, KatieMSB requested changes

2022-06-29 20:44 UTC, KatieMSB commented on web/src/app/lists/DraggableListItem.tsx
> +    <div ref={setNodeRef} style={style} {...attributes} {...listeners}>
Looks like the listeners here are blocking the event for the other actions button for the rotation users list.

2022-07-26 18:55 UTC, Forfold commented
group review: reverse the states as in always show edit controls, toggle button hides them, and then shows drag handles. move edit toggle to the left/in line with avatars

2022-10-05 21:31 UTC, Forfold commented
merged latest from master and wrapped up flipping the state of the toggle from the outcome of the group review, so this should be good to go again! @KatieMSB @tony-tvu

2022-10-07 15:39 UTC, Forfold commented
good catch @tony-tvu! i think that's a focus issue- once focused on the list item you should be able to tab again to focus on the drag handle. when i migrated it to FlatList i forgot about that

2022-10-07 17:46 UTC, tony-tvu approved these changes
lgtm!

2022-10-07 20:23 UTC, Forfold commented
whoops, needed to update the tests too @tony-tvu my bad! should be good to go now. running a full make check on my end to make sure the rest passes

2022-10-07 21:28 UTC, KatieMSB requested changes

2022-10-07 21:28 UTC, KatieMSB commented on web/src/app/lists/FlatList.tsx
> +  )
```suggestion
  const [dndItems, setDndItems] = useState(
    // use IDs to sort, fallback to index
    items.map((i, idx) => (i.id ? i.id : idx.toString())),
  )
  
  useEffect(() => {
    setDndItems(items.map((i, idx) => (i.id ? i.id : idx.toString())))
  }, [items])
```

The `dndItems` can get out of sync with the list `items` if users are removed from the rotation, adding a useEffect to keep updating on change seems to fix it

2022-10-12 18:07 UTC, KatieMSB approved these changes

2022-10-12 20:56 UTC, tony-tvu approved these changes

2022-10-12 21:03 UTC, merged