ui/schedules: remove timezone filter and add local time hover
target/goalert pull request #2416
Opened 2022-05-26 20:05 UTC by tony-tvu

- [x] Identified the issue which this PR solves.
- [x] Read the [**CONTRIBUTING**](https://github.com/target/goalert/blob/master/CONTRIBUTING.md) document.
- [x] Code builds clean without any errors or warnings.
- [x] Added appropriate tests for any new functionality.
- [x] All new and existing tests passed.
- [x] Added comments in the code, where necessary.
- [x] Ran `make check` to catch common errors. Fixed any that came up.

**Description:**
This PR removes the timezone filter switch on ScheduleShiftList component. Additionally, timezone abbreviations and a Tooltip have been added to the subtexts. Hovering over the date will display the user's local timezone date (unless the schedule and user's timezone match), while the default date display's the schedule's timezone date.

**Which issue(s) this PR fixes:**
https://github.com/target/goalert/issues/2402

**Screenshots:**
Europe/Berlin times BEFORE changes:
![europe](https://user-images.githubusercontent.com/52386267/170566582-9f027256-0ce4-4530-8548-dbe3080f0a41.png)

Local times BEFORE changes:
![local](https://user-images.githubusercontent.com/52386267/170566478-ca17a7e8-d4ee-47d7-a499-7095577e000c.png)

AFTER changes - These can be used to compare with Europe/Berlin and local screenshot times above to verify displayed and hovered times match. Please note that the hovered times are displayed **below** the displayed shift time. 

1.
![1](https://user-images.githubusercontent.com/52386267/170567516-087f44b0-3c67-433b-9b9c-b69dd0a0b977.png)

2.
![2](https://user-images.githubusercontent.com/52386267/170568102-c89af378-a1ec-44e2-b8eb-bef0e96db26b.png)

3.
![3](https://user-images.githubusercontent.com/52386267/170568125-06d9ecf0-28d2-4ab2-8531-a0749ef5ccb3.png)

4.
![4](https://user-images.githubusercontent.com/52386267/170568134-70ab7093-30a2-44d6-9ab7-6915c5ab1bc4.png)

5.
![5](https://user-images.githubusercontent.com/52386267/170568147-5341189f-27ff-4359-bf19-ec74ce89dd5b.png)

6.
![6](https://user-images.githubusercontent.com/52386267/170568161-22bd902d-75a8-4659-b226-5af16d4c7066.png)

7.
![7](https://user-images.githubusercontent.com/52386267/170568167-bd2345f9-f049-4980-9837-3fa79d926b05.png)

2022-06-01 20:35 UTC, KatieMSB submitted a review, later dismissed

2022-06-17 16:15 UTC, Forfold approved these changes
works great! thanks for updating the test support code, too 👍

2022-06-17 16:15 UTC, Forfold commented on web/src/app/schedules/ScheduleShiftList.js
> +    })
you could probably re-use the hour/minute code so you don't have to write that out each time here

```
const locale = {
  hour: 'numeric',
  minute: 'numeric',
}

const startTime = s.start.toLocaleString(locale)
const endTime = s.end.toLocaleString(locale)
const localStartTime = DateTime.fromISO(s.start, { zone: 'local' }).toLocaleString(locale)
const localEndTime = DateTime.fromISO(s.end, { zone: 'local' }).toLocaleString(locale)

2022-06-17 19:36 UTC, Forfold submitted a review, later dismissed

2022-06-27 19:31 UTC, KatieMSB requested changes

2022-06-27 19:31 UTC, KatieMSB commented on web/src/cypress/integration/schedules.ts
> -      cy.get('[data-cy="shift-details"]').trigger('mouseover')
We should keep `trigger('mouseover')` here, `focus()` won't trigger the tooltip to show up

2022-06-28 17:05 UTC, KatieMSB approved these changes

2022-07-05 16:42 UTC, tony-tvu commented
As of 7/5/22, we're waiting on the [playwright branch ](https://github.com/target/goalert/tree/playwright) to get merged before re-opening this PR. Playwright will allow us to test for different timezone conversions which is needed for the changes in this PR.

2022-10-12 20:59 UTC, Forfold submitted a review, later dismissed
lgtm!

2022-10-12 21:20 UTC, Forfold submitted a review, later dismissed

2022-11-09 16:15 UTC, Forfold commented on test/integration/timepickers.spec.ts
> +  await expect(page.locator('text=1/2/2006')).toContainText('1/2/2006')
Yeah, when the check functions are separated out they can be easy to miss 🐟  Sounds good!

2023-02-27 21:06 UTC, KatieMSB submitted a review, later dismissed

2023-02-27 21:22 UTC, mastercactapus commented on web/src/app/schedules/ScheduleShiftList.js
> +            'aria-label': 'local-timezone-tooltip',
aria-label should be left out for these -- the screen reader should read the contents of the tooltip

2023-03-30 20:24 UTC, AlaricWhitney commented
@tony-tvu if the conflicts are resolved, I can review it.

2023-04-06 16:57 UTC, AlaricWhitney requested changes
look good.  just minor comments

2023-04-06 16:57 UTC, AlaricWhitney commented on web/src/app/schedules/ScheduleShiftList.tsx
> +  function getShiftDetails(
it would be helpful to have a quick one line comment giving the gist of the purpose of the function.

2023-04-11 20:07 UTC, KatieMSB approved these changes

2023-04-11 20:08 UTC, merged