ui/schedules: convert ScheduleNewOverrideFAB & ScheduleOverrideCreateDialog to ts
target/goalert pull request #2457
Opened 2022-06-16 19:31 UTC by tony-tvu

- [x] Identified the issue which this PR solves.
- [x] Read the [**CONTRIBUTING**](https://github.com/target/goalert/blob/master/CONTRIBUTING.md) document.
- [x] Code builds clean without any errors or warnings.
- [x] Added appropriate tests for any new functionality.
- [x] All new and existing tests passed.
- [x] Added comments in the code, where necessary.
- [x] Ran `make check` to catch common errors. Fixed any that came up.

**Description:**
Part of an ongoing effort to convert existing javascript files to typescript.

**Which issue(s) this PR fixes:**
https://github.com/target/goalert/issues/2318

2022-06-17 18:37 UTC, KatieMSB approved these changes

2022-06-17 18:48 UTC, Forfold requested changes

2022-06-17 18:48 UTC, Forfold commented on web/src/app/schedules/ScheduleOverrideCreateDialog.tsx
> +  } = props
we could destructure this inside of the function params and get rid of using `props` as a variable all together

```
export default function ScheduleOverrideCreateDialog({
    scheduleID,
    variant,
    onClose,
    removeUserReadOnly,
    defaultValue = {},
  }: ScheduleOverrideCreateDialogProps,
): JSX.Element {
  
```

2022-06-17 18:48 UTC, Forfold commented on web/src/app/schedules/ScheduleOverrideCreateDialog.tsx
> +interface DefaultValue {
it doesn't look like the two files that render this component pass a `defaultValue` props. I'm thinking we can delete this and its references

2022-06-21 14:14 UTC, KatieMSB approved these changes

2022-06-21 14:58 UTC, Forfold approved these changes

2022-06-21 14:58 UTC, merged