ui/wizard: fix wizard character limit
target/goalert pull request #2515
Opened 2022-07-19 20:53 UTC by tony-tvu

- [x] Identified the issue which this PR solves.
- [x] Read the [**CONTRIBUTING**](https://github.com/target/goalert/blob/master/CONTRIBUTING.md) document.
- [x] Code builds clean without any errors or warnings.
- [x] Added appropriate tests for any new functionality.
- [x] All new and existing tests passed.
- [x] Added comments in the code, where necessary.
- [x] Ran `make check` to catch common errors. Fixed any that came up.

**Description:**
- This PR fixes the issue where a 64 character limit exceeded error occurred whenever users entered a name less than 64 characters but exceeded the limit whenever suffixes or timezones were appended. 
- Suffixes are no longer appended, i.e. "Service", "Escalation Policy", "Rotation"
- "Primary" and "Secondary" keywords are appended only if a service has two schedules
- Rotations that have Follow the Sun (FTS) support will have their timezones appended to the **rotation's name**. This solution was implemented to resolve `Name: already in use` errors whenever a schedule is created with FTS support that has a rotation with a timezone different than its original timezone, which resulted in two rotations with the same names sent to the backend. 
- Name length validation error messages are now customized based on user's needs. For example, if a user creates a service with one schedule without FTS, then they will see `cannot be more than 64 characters` error when they've exceeded the limit. If a user creates a service that has two schedules without FTS, then they will see `cannot be more than 54 characters` error since ' Secondary' is an additional 10 characters subtracted from 64. These scenarios are accounted for in this PR's cypress test.

**Which issue(s) this PR fixes:**
https://github.com/target/goalert/issues/2488

2022-10-07 18:39 UTC, KatieMSB approved these changes
lgtm

2022-10-07 19:31 UTC, KatieMSB requested changes
Unit tests ( `app/wizard/util.test.js`) for the wizard also need updated to reflect the new expected output

2022-10-11 14:41 UTC, KatieMSB approved these changes

2022-10-13 21:02 UTC, Forfold approved these changes

2022-10-13 21:02 UTC, merged