ui/selection: display email as subtext on user select
target/goalert pull request #2520
Opened 2022-07-21 20:58 UTC by tony-tvu

- [x] Identified the issue which this PR solves.
- [x] Read the [**CONTRIBUTING**](https://github.com/target/goalert/blob/master/CONTRIBUTING.md) document.
- [x] Code builds clean without any errors or warnings.
- [x] Added appropriate tests for any new functionality.
- [x] All new and existing tests passed.
- [x] Added comments in the code, where necessary.
- [x] Ran `make check` to catch common errors. Fixed any that came up.

**Description:**
This PR adds email as a subtext when selecting users to add to a rotation or escalation policy step. This allows  differentiating between users with the same display names. 

**Which issue(s) this PR fixes:**
https://github.com/target/goalert/issues/2496

**Screenshots:**

BEFORE:
<img width="2212" alt="before" src="https://user-images.githubusercontent.com/52386267/180313828-f3aabbf7-b9a8-494a-b927-be36bcd2f99b.png">

AFTER:

![Emails as subtext](https://user-images.githubusercontent.com/52386267/180313849-15c06240-cb3d-4745-9308-d6d8a23b8953.png)

<img width="2208" alt="Screen Shot 2022-07-21 at 3 55 46 PM" src="https://user-images.githubusercontent.com/52386267/180313867-9206b912-f819-4cb9-9cb6-a423d95d2037.png">

2022-07-25 14:00 UTC, mastercactapus requested changes

2022-07-25 14:00 UTC, mastercactapus commented on web/src/app/selection/QuerySelect.js
> +  email: subText,
Override this prop in `UserSelect` instead of changing the default

2022-07-25 18:31 UTC, mastercactapus approved these changes

2022-07-26 18:42 UTC, Forfold approved these changes
lgtm - group review during mob session

2022-07-26 18:42 UTC, merged