auth: link slack user
target/goalert pull request #2564
Opened 2022-08-17 15:58 UTC by tony-tvu

- [x] Identified the issue which this PR solves.
- [x] Read the [**CONTRIBUTING**](https://github.com/target/goalert/blob/master/CONTRIBUTING.md) document.
- [x] Code builds clean without any errors or warnings.
- [x] Added appropriate tests for any new functionality.
- [x] All new and existing tests passed.
- [x] Added comments in the code, where necessary.
- [x] Ran `make check` to catch common errors. Fixed any that came up.

**Description:**
This PR facilitates linking slack users to their GoAlert accounts, which would allow them to acknowledge or close an alert from the Slack UI once linked.

**Out of Scope:**
Devtool's mock slack server has been updated to account for block elements

**Screenshots:**
1. Alert sent to unlinked slack user
<img width="874" alt="Screen Shot 2022-08-17 at 10 49 34 AM" src="https://user-images.githubusercontent.com/52386267/185186040-6f24545c-9c19-4051-9a3f-543fac207c2e.png">

2. Clicking 'Link Account' button routes them to GoAlert's profile page to confirm linking
<img width="2552" alt="Screen Shot 2022-08-17 at 10 50 40 AM" src="https://user-images.githubusercontent.com/52386267/185186215-3782cba7-1342-4369-88d9-989ba548aaa3.png">

3. Once linking is confirmed, it'll automatically acknowledge or close the alert based on the selection at stage 1
<img width="2277" alt="Screen Shot 2022-08-17 at 10 51 01 AM" src="https://user-images.githubusercontent.com/52386267/185186405-f9b5e33b-851f-4821-ad05-91fcdc34594f.png">

<img width="875" alt="Screen Shot 2022-08-17 at 10 51 48 AM" src="https://user-images.githubusercontent.com/52386267/185186611-5fff6eff-d3fa-4eb1-b238-b5870e741b34.png">

4. Linked user can now Close the alert from the slack UI
<img width="879" alt="Screen Shot 2022-08-17 at 10 52 00 AM" src="https://user-images.githubusercontent.com/52386267/185186640-c3b36296-1ecd-475b-aeb8-8ee870baf6fc.png">

2022-08-22 21:16 UTC, mastercactapus requested changes
Here's what I think we have left:
- Update the messaging to be a little more informative, like: "Slack user <User.Name> (@<User.Username>) from <Team.Domain>.slack.com"
- We should show errors in the dialog before closing (e.g., network issue)
- Unknown/invalid/expired tokens should have consistent messaging
- We should probably add the details in the token, or at least a signature -- it's too easy to make a URL that will link a user in a way they didn't expect; we can have a query to validate the token before the user confirms

2022-08-22 22:49 UTC, mastercactapus commented
I moved the metadata to a table column, that way, to get _any_ info, you need a valid GoAlert session AND the token/url, and also handles ensuring the messaging the user gets is also validated and isn't subject to a malicious/misleading link.

2022-08-29 17:34 UTC, mastercactapus approved these changes

2022-08-31 12:51 UTC, mastercactapus approved these changes
Leaving integration test out-of-scope; we'll add that as a test when the mockslack server gains a UI

2022-09-06 21:20 UTC, KatieMSB approved these changes

2022-09-06 21:21 UTC, merged