ui/services: convert IntegrationKeyCreateDialog to ts
target/goalert pull request #2568
Opened 2022-08-18 16:32 UTC by tony-tvu

- [x] Identified the issue which this PR solves.
- [x] Read the [**CONTRIBUTING**](https://github.com/target/goalert/blob/master/CONTRIBUTING.md) document.
- [x] Code builds clean without any errors or warnings.
- [x] Added appropriate tests for any new functionality.
- [x] All new and existing tests passed.
- [x] Added comments in the code, where necessary.
- [x] Ran `make check` to catch common errors. Fixed any that came up.

**Description:**
Part of an ongoing effort to convert existing javascript files to typescript.

**Which issue(s) this PR fixes:**
https://github.com/target/goalert/issues/2318

**Out of Scope:**
- switch out Apollo client with urql

2022-09-08 14:44 UTC, KatieMSB requested changes

2022-09-08 14:44 UTC, KatieMSB commented on web/src/app/services/IntegrationKeyList.tsx
> +          else={<div>Email integration keys are currently disabled.</div>}
```suggestion
          else={
            <React.Fragment>
              Email integration keys are currently disabled.
            </React.Fragment>
          }
```
Looks like the `<div>` here is throwing an error

<img width="464" alt="Screen Shot 2022-09-08 at 9 44 22 AM" src="https://user-images.githubusercontent.com/38022260/189152575-1ff5fa3f-004b-4d0d-89db-f677cd40cf3a.png">

2022-09-23 20:48 UTC, KatieMSB submitted a review, later dismissed

2022-10-03 19:51 UTC, KatieMSB submitted a review, later dismissed

2022-10-07 20:55 UTC, Forfold commented on web/src/app/services/IntegrationKeyCreateDialog.tsx
> +    useMutation(mutation)
just a suggestion, might read easier to shorten the names here

```suggestion
  const [createKeyStatus, createKey] =
    useMutation(mutation)
```

2022-10-07 20:56 UTC, Forfold commented on web/src/app/services/IntegrationKeyList.tsx
> +interface Item {
let's import and use the `FlatListListItem` type instead

2022-10-07 20:57 UTC, Forfold requested changes
just a couple small things ^ otherwise looks good

2022-10-13 21:15 UTC, Forfold submitted a review, later dismissed

2022-10-13 21:22 UTC, KatieMSB approved these changes

2022-10-13 21:25 UTC, Forfold approved these changes

2022-10-13 21:45 UTC, merged