ui/schedules: converting ScheduleOverrideForm to typescript
target/goalert pull request #2706
Opened 2022-11-29 18:08 UTC by nataliekorzh

- [x] Identified the issue which this PR solves.
- [x] Read the [**CONTRIBUTING**](https://github.com/target/goalert/blob/master/CONTRIBUTING.md) document.
- [x] Code builds clean without any errors or warnings.
- [x] Added appropriate tests for any new functionality.
- [x] All new and existing tests passed.
- [x] Added comments in the code, where necessary.
- [x] Ran `make check` to catch common errors. Fixed any that came up.

**Description:**
Converting the `ScheduleOverrideForm` component to Typescript.

**Which issue(s) this PR fixes:**
Part of #2318

2022-11-30 21:59 UTC, tony-tvu requested changes

2022-11-30 21:59 UTC, tony-tvu commented on web/src/app/schedules/ScheduleOverrideForm.tsx
> +  onChange?: (value: ScheduleOverrideFormValue) => void
Looks like `onChange` was required before the conversion. 
```suggestion
  onChange: (value: ScheduleOverrideFormValue) => void
```

2022-12-05 18:37 UTC, tony-tvu approved these changes
LGTM!

2022-12-07 20:16 UTC, mastercactapus approved these changes

2022-12-07 20:16 UTC, merged