ui: add desktop service create buttons
target/goalert pull request #2735
Opened 2022-12-09 20:01 UTC by Forfold

Part of #2715

Adds create buttons when on wide browser width for:
- Heartbeat monitors
- Labels
- Integration Keys

- Adds a header note for the service labels list

2022-12-19 18:44 UTC, johnmarksilly requested changes
Typo but good otherwise

2022-12-19 18:44 UTC, johnmarksilly commented on web/src/app/services/ServiceLabelList.tsx
> +        headerNote='Labels are a way associate services with each other throughout GoAlert. Search using the format key1/key2=value'
Typo on this line.

2022-12-19 18:59 UTC, Forfold commented on web/src/app/services/ServiceLabelList.tsx
> +        headerNote='Labels are a way associate services with each other throughout GoAlert. Search using the format key1/key2=value'
```suggestion
        headerNote='Labels are a way to associate services with each other throughout GoAlert. Search using the format key1/key2=value'
```

2022-12-19 20:54 UTC, mastercactapus approved these changes

2022-12-20 18:29 UTC, johnmarksilly approved these changes

2022-12-20 18:36 UTC, merged