feat: adding error checks to app methods
target/goalert pull request #2903
Opened 2023-03-24 21:33 UTC by AlaricWhitney

- [x] Identified the issue which this PR solves.
- [x] Read the [**CONTRIBUTING**](https://github.com/target/goalert/blob/master/CONTRIBUTING.md) document.
- [x] Code builds clean without any errors or warnings.
- [x] Added appropriate tests for any new functionality.
- [x] All new and existing tests passed.
- [x] Added comments in the code, where necessary.
- [x] Ran `make check` to catch common errors. Fixed any that came up.

**Description:**
Adding error checks to the `app` methods.

**Which issue(s) this PR fixes:**
https://github.com/target/goalert/issues/2579

**Out of Scope:**
adding any complexity to existing methods.

**Screenshots:**
NA

**Describe any introduced user-facing changes:**
NA

**Describe any introduced API changes:**
NA

**Additional Info:**
NA

2023-03-24 22:04 UTC, mastercactapus requested changes

2023-03-27 14:42 UTC, AlaricWhitney commented on app/lifecycle/manager_test.go
> +	go func(mgr *Manager) { _ = mgr.Run(context.Background()) }(mgr)
we can't, because we can't pass `t *testing.T` into a goroutine.

2023-03-27 14:45 UTC, AlaricWhitney commented on app/lifecycle/manager_test.go
> +	_ = mgr.SetPauseResumer(pr)
we can't do the helper function, because we can't pass `t *testing.T` into a goroutine.  I can assert no error though.

2023-03-27 14:47 UTC, AlaricWhitney commented on app/concurrencylimiter_test.go
> +	go func(ctx context.Context) { _ = wait(ctx) }(ctx)
done

2023-03-27 14:48 UTC, AlaricWhitney commented on app/cmd.go
> +				_ = store.Shutdown(ctx)
done

2023-03-27 15:12 UTC, mastercactapus commented on app/lifecycle/manager_test.go
> +	go func(mgr *Manager) { _ = mgr.Run(context.Background()) }(mgr)
That's not entirely correct, there are only certain methods restricted to the parent goroutine, due to how they are implemented. All others are safe.

Refer to the documentation for which:
https://pkg.go.dev/testing#T

2023-03-28 20:36 UTC, AlaricWhitney commented on app/lifecycle/manager_test.go
> +	_ = mgr.SetPauseResumer(pr)
instead i did `require.NoError(t, mgr.SetPauseResumer(pr))`, which I think it clean.

2023-03-28 20:38 UTC, AlaricWhitney commented on app/lifecycle/manager_test.go
> +	go func(mgr *Manager) { _ = mgr.Run(context.Background()) }(mgr)
hmm, the linter didn't freak out.  done, and imported `t *testing.T` to ensure nothing is lost.

2023-03-29 17:41 UTC, mastercactapus commented on app/lifecycle/manager_test.go
> +	go func(t *testing.T, mgr *Manager) { assert.NoError(t, mgr.Run(context.Background())) }(t, mgr)
```suggestion
	go func() { assert.NoError(t, mgr.Run(context.Background())) }()
```

2023-03-29 17:42 UTC, mastercactapus commented on app/lifecycle/manager_test.go
> +	go func(t *testing.T, mgr *Manager) { assert.NoError(t, mgr.Run(context.Background())) }(t, mgr)
```suggestion
	go func() { assert.NoError(t, mgr.Run(context.Background())) }()
```

2023-03-29 17:42 UTC, mastercactapus commented on app/lifecycle/manager_test.go
> +	go func(t *testing.T, mgr *Manager) { assert.NoError(t, mgr.Run(context.Background())) }(t, mgr)
```suggestion
	go func() { assert.NoError(t, mgr.Run(context.Background())) }()
```

2023-03-29 21:00 UTC, mastercactapus submitted a review, later dismissed

2023-04-25 20:03 UTC, cmarquis submitted a review, later dismissed

2023-04-25 20:08 UTC, allending313 submitted a review, later dismissed
LGTM

2023-04-25 20:31 UTC, mastercactapus requested changes

2023-04-25 21:05 UTC, AlaricWhitney commented on app/prometheus.go
> +	go func(l *net.Listener) { _ = srv.Serve(*l) }(&l)
I'm doing it to fool the linter, as I can't just pass `l` in by itself (dereference error).  I can just not pass in `l` and just reference it directly in the goroutine if that's what you prefer.

2023-04-25 21:58 UTC, mastercactapus commented on app/prometheus.go
> +	go func(l *net.Listener) { _ = srv.Serve(*l) }(&l)
I think the issue before was that my previous code suggestion mistakenly kept the `*` in there, which gave the dereference error.

2023-04-25 21:58 UTC, mastercactapus approved these changes

2023-04-26 19:41 UTC, allending313 approved these changes

2023-04-27 19:16 UTC, AlaricWhitney commented
fixed so that tests pass now

2023-04-27 19:55 UTC, allending313 approved these changes

2023-04-27 20:15 UTC, KatieMSB approved these changes

2023-04-27 20:46 UTC, merged