ui: add slack user groups to on call notifications
target/goalert pull request #2932
Opened 2023-04-11 20:33 UTC by Forfold

**Description:**
This PR introduces the ability to create an on-call notification rule that simultaneously keeps a slack user group in sync with the list of GoAlert on-call users

**Which issue(s) this PR fixes:**
Closes #1228

**Screenshots:**
<img width="623" alt="Screenshot 2023-04-11 at 3 29 13 PM" src="https://user-images.githubusercontent.com/11381794/231281459-f2ad4f5b-a988-4564-9f4e-a4253ae9f693.png">

<img width="699" alt="Screenshot 2023-04-11 at 3 29 18 PM" src="https://user-images.githubusercontent.com/11381794/231281477-2f03abe8-d4c7-4541-9493-dd1e167abca8.png">

<img width="712" alt="Screenshot 2023-04-11 at 3 29 07 PM" src="https://user-images.githubusercontent.com/11381794/231281500-cdcbb6eb-3ea0-4904-87a8-6f5ca1ea85e0.png">

2023-04-11 20:34 UTC, Forfold commented
Currently includes changes from #2926. Let's get that merged first.

2023-04-18 13:46 UTC, AlaricWhitney requested changes

2023-04-18 13:46 UTC, AlaricWhitney commented on notification/slack/usergrouperror.go
> +	urlStr := e.callbackFunc("schedules/" + url.PathEscape(e.ScheduleID))
To promote good secure coding habits, we should never directly concatenate strings.
```suggestion
	urlStr := e.callbackFunc(fmt.Sprintf("schedules/%s", url.PathEscape(e.ScheduleID)))
```

2023-04-18 13:46 UTC, AlaricWhitney commented on notification/slack/usergroupsender.go
> +	err = s.cfg.UserStore.AuthSubjectsFunc(ctx, "slack:"+teamID, userIDs, func(sub user.AuthSubject) error {
To promote good secure coding habits, we should never directly concatenate strings.
```suggestion
	err = s.cfg.UserStore.AuthSubjectsFunc(ctx, fmt.Sprintf("slack:%s", teamID), userIDs, func(sub user.AuthSubject) error {
```

2023-04-20 16:34 UTC, AlaricWhitney approved these changes
LGTM

2023-04-20 20:19 UTC, mastercactapus commented
Switching this to draft while blocked, #2926 has API changes that need to be settled first.

2023-04-26 21:58 UTC, mastercactapus requested changes
This is still visible without the feature flag set, let's add a guard around that. EP step UI has an example of how to do this for webhooks.

Also, couple of layout questions:
- Should we move the input fields below the notification option? I feel the input should follow the context. Also, we may be adding webhook support here soon, so it will help prepare for more noise.
- Can we put a checkbox in for the user group and conditionally show the input field? I think that might reduce noise in the form while still keeping it clear how to opt-in to the new feature.

2023-05-01 20:16 UTC, mastercactapus approved these changes

2023-05-01 20:16 UTC, mastercactapus commented on Makefile
> -	yarn set version stable
This is no longer needed with #2984

2023-05-01 21:04 UTC, AlaricWhitney approved these changes

2023-05-01 21:12 UTC, merged