ui/AlertDetailLogs: Convert to typescript
target/goalert pull request #2935
Opened 2023-04-12 14:52 UTC by KatieMSB

- [x] Identified the issue which this PR solves.
- [x] Read the [**CONTRIBUTING**](https://github.com/target/goalert/blob/master/CONTRIBUTING.md) document.
- [x] Code builds clean without any errors or warnings.
- [x] Added appropriate tests for any new functionality.
- [x] All new and existing tests passed.
- [x] Added comments in the code, where necessary.
- [x] Ran `make check` to catch common errors. Fixed any that came up.

**Description:**
Convert <AlertDetailLogs /> component to typescript.
Part of #2318

2023-04-12 20:12 UTC, mastercactapus requested changes

2023-04-12 20:12 UTC, mastercactapus commented on web/src/app/alerts/AlertDetailLogs.tsx
> +  const getLogStatusClass = (status: string): string => {
Can we change this to `NotificationStatus` and add a check that the switch is exhaustive?

2023-04-12 20:12 UTC, mastercactapus commented on web/src/app/alerts/AlertDetailLogs.tsx
> +    event: {
Could this be `event: AlertLogEntry`?

2023-04-17 17:40 UTC, mastercactapus submitted a review, later dismissed

2023-04-18 13:37 UTC, AlaricWhitney approved these changes

2023-04-24 12:38 UTC, AlaricWhitney approved these changes

2023-04-25 18:36 UTC, cmarquis approved these changes

2023-04-25 19:16 UTC, merged