sms: Allow multi-segment messages
target/goalert pull request #3073
Opened 2023-06-06 19:55 UTC by mastercactapus

**Description:**
Updates the SMS code to fallback to sending multi-segment messages instead of refusing delivery.

The SMS code will truncate the details of an alert to try to fit it into a single segment (160 characters) message. When this isn't possible, it will attempt to truncate into 2 segments, and then three, etc...

The factors that control the minimum message size are configured at the admin level, application name, public URL, and related options. Fields such as alert summary and service name (user controlled) are subject to truncation.

This ensures user misconfiguration won't cause many message segments to go out but allows alerts to be sent in cases where the public URL, for instance, is too long for certain message types to fit.

**Which issue(s) this PR fixes:**
Fixes #3058 

**Out of Scope:**
- No changes to the rate limit/throttling code are made to account for extra segments.

**Additional context**
- The full SMS message is now rendered in the template. Previously, the application name was added as a prefix after calculation.

2023-06-13 18:15 UTC, tony-tvu requested changes

2023-06-13 18:15 UTC, tony-tvu commented on notification/twilio/alertsms.go
>  // truncated (if needed) until the output is <= maxLen characters.
Can these comments be updated since `maxLen` has been changed to `appName`? It's a bit unclear now.

2023-06-14 19:31 UTC, tony-tvu approved these changes
LGTM

2023-06-14 20:59 UTC, Forfold commented on notification/twilio/alertsms.go
> +// renderAlertBundleMessage will render a SMS message for an Alert Bundle.
nit
```suggestion
// renderAlertBundleMessage will render an SMS message for an Alert Bundle.
```

2023-06-14 21:16 UTC, tony-tvu approved these changes

2023-06-14 21:53 UTC, merged