sending alert object as create alert response body
target/goalert pull request #3124
Opened 2023-06-26 07:13 UTC by sudhabindu-apm

- [x] Identified the issue which this PR solves.
- [x] Read the [**CONTRIBUTING**](https://github.com/target/goalert/blob/master/CONTRIBUTING.md) document.
- [x] Code builds clean without any errors or warnings.
- [ ] Added appropriate tests for any new functionality.
- [x] All new and existing tests passed.
- [ ] Added comments in the code, where necessary.
- [x] Ran `make check` to catch common errors. Fixed any that came up.

**Description:**
This PR adds the sends the created alert as response body in create alert generic API.

**Which issue(s) this PR fixes:**
Fixes https://github.com/target/goalert/issues/3123

**Screenshots:**
<img width="1624" alt="Screenshot 2023-06-26 at 12 41 54 PM" src="https://github.com/target/goalert/assets/137173845/d25890d4-e013-4a35-907f-1425b3382ab1">

**Describe any introduced API changes:**
This PR changes the response of the createAlert API  (`POST /api/v2/generic/incoming`) from 204 to 200 with the alert object as the payload.

2023-07-17 05:29 UTC, sudhabindu-apm commented
@mastercactapus  I have made the requested changes.

2023-07-17 19:22 UTC, mastercactapus requested changes

2023-07-17 19:22 UTC, mastercactapus commented on genericapi/handler.go
> +	errutil.HTTPError(ctx, w, errors.Wrap(err, "create alert send payload"))
This can be ignored, since the remote side has presumably already terminated the connection
```suggestion
	_,_ = w.Write(data)
```

2023-07-17 19:22 UTC, mastercactapus commented on genericapi/handler.go
> +	_, err = w.Write(data)
Set the content-type header before sending the response

2023-07-17 19:22 UTC, mastercactapus commented on genericapi/handler.go
> +		createdAlert, err := h.c.AlertStore.CreateOrUpdate(ctx, a)
We'll need to update `CreateOrUpdate` to return the `isNew` value as `createdAlert.Dedup` is the dedup hash, and will never be `nil`

2023-07-18 12:30 UTC, sudhabindu-apm commented
@mastercactapus  I have made the required changes. I have changed the `IsDuplicate` parameter of the returned object to `isNew` as `CreateOrUpdate` is returning that so that we don't do unnecessary negation.

2023-07-19 15:59 UTC, mastercactapus approved these changes

2023-07-19 16:56 UTC, allending313 approved these changes
lgtm!

2023-07-19 17:40 UTC, merged

2023-07-20 04:58 UTC, sudhabindu-apm commented
Thank you!