feat: add integration test for slack usergroup feat
target/goalert pull request #3129
Opened 2023-06-26 20:47 UTC by allending313

- [x] Identified the issue which this PR solves.
- [ ] Read the [**CONTRIBUTING**](https://github.com/target/goalert/blob/master/CONTRIBUTING.md) document.
- [ ] Code builds clean without any errors or warnings.
- [ ] Added appropriate tests for any new functionality.
- [ ] All new and existing tests passed.
- [ ] Added comments in the code, where necessary.
- [ ] Ran `make check` to catch common errors. Fixed any that came up.

**Description:**
Added happy path integration test in cypress to test slack user group usability in the ui. This included additions to mockslack to support usergroup.list api calls.

https://jira.target.com/browse/NSP-384

2023-06-27 19:15 UTC, mastercactapus requested changes

2023-06-27 19:15 UTC, mastercactapus commented on devtools/mockslack/usergroupslist.go
> +func (st *API) UserGroupList(ctx context.Context) ([]UserGroup, error) {
Add comments to these matching the ones we have in `conversations.list`, for example

2023-06-27 19:15 UTC, mastercactapus commented on web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsForm.tsx
> +            data-cy='select-notification-type'
can we use the name field instead?

2023-06-28 20:06 UTC, mastercactapus approved these changes

2023-06-28 20:29 UTC, cmarquis approved these changes

2023-06-29 15:47 UTC, merged