api: add base admin API key support
target/goalert pull request #3274
Opened 2023-09-12 21:35 UTC by mastercactapus

**Description:**
This PR introduces the ability to create, delete, and use admin-only API keys for the GraphQL API.

This functionality is behind the experimental flag `gql-api-keys`.

`make start EXPERIMENTAL=gql-api-keys`

**Which issue(s) this PR fixes:**
Part of #3007 

**Out of Scope:**
- Policy caching (perf. optimization) will be done in a second PR
- Update and listing will be done in a separate PR, this is just base functionality
- UI for managing and viewing usage will be done in a separate PR

**Describe any introduced API changes:**
- `createGQLAPIKey` and `deleteGQLAPIKey` mutations were added

2023-09-13 21:40 UTC, andrewbenington approved these changes
looks good and seems to work well locally

2023-09-13 21:52 UTC, andrewbenington requested changes
looks like `expflag.d.ts` and `schema.d.ts` are out of date, running `go generate ./web/src` updated them for me

2023-09-14 15:21 UTC, andrewbenington approved these changes

2023-09-20 15:59 UTC, KatieMSB approved these changes

2023-09-20 16:49 UTC, merged