ui/admin: add service metrics data table
target/goalert pull request #3368
Opened 2023-10-16 19:39 UTC by KatieMSB

- [x] Identified the issue which this PR solves.
- [x] Read the [**CONTRIBUTING**](https://github.com/target/goalert/blob/master/CONTRIBUTING.md) document.
- [x] Code builds clean without any errors or warnings.
- [x] Added appropriate tests for any new functionality.
- [x] All new and existing tests passed.
- [x] Added comments in the code, where necessary.
- [x] Ran `make check` to catch common errors. Fixed any that came up.

**Description:**
This PR adds part of the service metrics ui work that includes overall metrics for all services and a table of all services.

**Which issue(s) this PR fixes:**
Part of #3057

**Out of Scope:**
- filtering
- integration key/escalation policy target metrics

**Screenshots:**
<img width="1680" alt="Screenshot 2023-10-16 at 1 23 02 PM" src="https://github.com/target/goalert/assets/38022260/93946058-3a95-435e-94e2-a09e665ffe58">

2023-10-16 20:44 UTC, tony-tvu requested changes

2023-10-16 20:44 UTC, tony-tvu commented on web/src/app/admin/admin-service-metrics/AdminServiceTable.tsx
> +            <AppLink to={`/services/${params.row.escalationPolicy.id}`}>
```suggestion
            <AppLink to={`/escalation-policies/${params.row.escalationPolicy.id}`}>
```

2023-10-16 20:46 UTC, KatieMSB commented on web/src/app/admin/admin-service-metrics/AdminServiceTable.tsx
> +            <AppLink to={`/services/${params.row.escalationPolicy.id}`}>
good catch 👍🏽

2023-10-16 21:12 UTC, tony-tvu approved these changes
LGTM

2023-10-17 18:38 UTC, tony-tvu submitted a review, later dismissed

2023-10-26 15:51 UTC, Forfold requested changes
As a subheader under Services, could we maybe have some loading text, such as "Loading... This may take a minute."

Also, this could maybe be iterated on later, but thinking about the top cards to be more responsive for various browser sizes. Maybe switch to `xs={6} sm={2.4}` or something?

Last thing, is perhaps setting the height to the top cards to 100% of their container, so their heights all match:

<img width="434" alt="Screenshot 2023-10-26 at 10 48 18 AM" src="https://github.com/target/goalert/assets/11381794/526ffd14-d92d-4a98-bf50-e05c73db9f01">

2023-10-26 16:27 UTC, Forfold approved these changes

2023-10-26 17:51 UTC, ethan-haynes approved these changes
LGTM 👍

2023-10-27 14:05 UTC, merged