Implement Duplicate Functionality for API Keys
target/goalert pull request #3395
Opened 2023-10-30 22:48 UTC by mastercactapus

**Description:**
This PR introduces a convenient "Duplicate" option for API keys within the GoAlert application. Users can now effortlessly create a new API key based on an existing one, streamlining key management and improving user efficiency. This feature applies to both active and expired keys, ensuring a continuous workflow. With user experience in mind, the duplication process is designed to be intuitive and seamless, mirroring the expiration characteristics of the source key relative to the current time.

**Which issue(s) this PR fixes:**
This is part of #3007 

**Out of Scope:**
Visual updates for expired keys and special sorting considerations for nearly expired keys are out of scope for this PR.

**Screenshots:**
![image](https://github.com/target/goalert/assets/595010/3f6e9f7f-427a-4e9d-921a-721803d404c2)

**Describe any introduced user-facing changes:**
Users will notice a new "Duplicate" option when managing API keys. This option allows the generation of a new key with an incremented name and an expiration period set to an equivalent duration from the current moment, just as the original key was set from its creation time.

**Describe any introduced API changes:**
N/A

**Additional Info:**
This PR also includes a fix for the previously unsorted API keys. Now, keys will be sorted by name, recognizing numeric values which will improve the findability and management of multiple keys. The "Duplicate" feature respects the expiration paradigm of the original key, maintaining consistency in key lifecycle management.

2023-10-31 17:50 UTC, Forfold requested changes
I spy an AI talking 👀 Functionally works but I'm noticing the state isn't clearing on exit, so when I go to create a new key, the previous data is still in the dialog

2023-11-01 14:31 UTC, ethan-haynes approved these changes

2023-11-01 15:05 UTC, Forfold approved these changes

2023-11-01 15:28 UTC, ethan-haynes approved these changes

2023-11-01 15:36 UTC, merged