users: use generic destinations for user CM create and edit dialog components
target/goalert pull request #3664
Opened 2024-02-09 18:16 UTC by tony-tvu

- [x] Identified the issue which this PR solves.
- [x] Read the [**CONTRIBUTING**](https://github.com/target/goalert/blob/master/CONTRIBUTING.md) document.
- [x] Code builds clean without any errors or warnings.
- [x] Added appropriate tests for any new functionality.
- [x] All new and existing tests passed.
- [x] Added comments in the code, where necessary.
- [x] Ran `make check` to catch common errors. Fixed any that came up.

**Description:**
This PR updates the UserContactMethod create and dialog components to use generic destinations when the experimental flag is set `make start EXPERIMENTAL=dest-types`.

**Which issue(s) this PR fixes:**
part of https://github.com/target/goalert/issues/2639

**Out of Scope:**
N/A

**Screenshots:**
<img width="1789" alt="Screenshot 2024-02-09 at 12 15 38 PM" src="https://github.com/target/goalert/assets/52386267/99488d47-94f9-4db0-b723-3561eb268067">
<img width="1788" alt="Screenshot 2024-02-09 at 12 15 30 PM" src="https://github.com/target/goalert/assets/52386267/11974495-a93d-4eac-80b7-364141a4c9e9">
<img width="1785" alt="Screenshot 2024-02-09 at 12 15 20 PM" src="https://github.com/target/goalert/assets/52386267/81bf8842-ca98-4876-a418-eedc8ded055c">
<img width="1788" alt="Screenshot 2024-02-09 at 12 15 11 PM" src="https://github.com/target/goalert/assets/52386267/38d16c37-f086-413b-a3fe-7a602183441c">
<img width="1787" alt="Screenshot 2024-02-09 at 12 14 57 PM" src="https://github.com/target/goalert/assets/52386267/dab7d1f5-cd22-4117-bf4e-981aa3f613b3">

**Describe any introduced user-facing changes:**
N/A, behavior should be the same as today.

**Describe any introduced API changes:**
N/A

**Additional Info:**
N/A

2024-02-09 19:58 UTC, mastercactapus requested changes
Noticed a couple issues when functionally testing:
- the docs page in storybook seems broken, maybe we disable those for dialogs? unless there's a way to fix (related issue: https://github.com/storybookjs/storybook/issues/16949 -- looks like some things to try)
- errors aren't being fed -- i.e., enter `123` as a phone number and the validation error doesn't display
- create dialog says status updates aren't supported for SMS which is incorrect

2024-02-09 20:24 UTC, mastercactapus commented
For the error stuff I think that's going to require a bit of extra thought; working on `dest-error-api` branch

2024-02-09 20:37 UTC, tony-tvu commented
> For the error stuff I think that's going to require a bit of extra thought; working on `dest-error-api` branch

Sounds good. Thanks for pushing up the fixes to this branch!

2024-02-22 19:23 UTC, mastercactapus approved these changes

2024-02-22 19:31 UTC, mastercactapus submitted a review, later dismissed

2024-02-22 19:36 UTC, mastercactapus approved these changes

2024-02-22 21:12 UTC, ethan-haynes approved these changes

2024-02-22 21:17 UTC, merged