users: use generic destinations for User Notification Rule List component
target/goalert pull request #3701
Opened 2024-02-22 19:06 UTC by ethan-haynes

- [x] Identified the issue which this PR solves.
- [x] Read the [**CONTRIBUTING**](https://github.com/target/goalert/blob/master/CONTRIBUTING.md) document.
- [x] Code builds clean without any errors or warnings.
- [x] Added appropriate tests for any new functionality.
- [x] All new and existing tests passed.
- [x] Added comments in the code, where necessary.
- [x] Ran `make check` to catch common errors. Fixed any that came up.

**Description:**
This PR updates the UserNotificationRuleList component to use generic destinations when the experimental flag is set make start EXPERIMENTAL=dest-types.

**Which issue(s) this PR fixes:**
part of https://github.com/target/goalert/issues/2639

**Out of Scope:**
N/A

**Screenshots:**
<img width="730" alt="Screenshot 2024-02-22 at 1 03 47 PM" src="https://github.com/target/goalert/assets/18644928/2eee4ffc-1700-4ebf-ae64-c38a0f7fad58">

**Describe any introduced user-facing changes:**
Once experimental flag dest-types is no longer required, user contact methods on the profile page will display new label singular values.

**Describe any introduced API changes:**
N/A

**Additional Info:**
N/A

2024-02-22 19:48 UTC, mastercactapus requested changes

2024-02-22 19:48 UTC, mastercactapus commented on web/src/app/users/UserNotificationRuleListDest.tsx
> +          }
We can limit this to just the fields we need, and also remove the unused bits from the stories data for less noise.
```suggestion
        contactMethod {
          id
          name
          dest {
            type
            displayInfo {
              text
              iconAltText
            }
          }
```

2024-02-22 21:02 UTC, mastercactapus approved these changes

2024-02-23 15:02 UTC, tony-tvu approved these changes

2024-02-23 15:02 UTC, merged