dev: update demo container for integration test usage
target/goalert pull request #3734
Opened 2024-03-08 21:02 UTC by mastercactapus

**Description:**
Makes a couple small updates to the demo container for integration test use-cases:
- Added a non-admin login
- Added the ability to skip the DB seed step when not necessary

**Additional Info:**
To validate with docker:
```bash
# build dependencies
make bin/goalert-linux-amd64.tgz bin/linux-amd64/resetdb

# build container
docker build -t gademo -f devtools/ci/dockerfiles/demo/Dockerfile.prebuilt --build-arg ARCH=amd64 .

# Run _with_ seed data
docker run -it --rm -p 8081:8081 gademo

# Run _without_ seed data
docker run -it --rm -p 8081:8081 -e SKIP_SEED=1 gademo
```

Both should allow login of admin/admin123 and user/user1234, with the latter skipping the random data generation (no services, rotations, etc...)

2024-03-08 21:04 UTC, Forfold approved these changes

2024-03-08 21:05 UTC, Forfold approved these changes

2024-03-11 20:12 UTC, ethan-haynes commented on README.md
> +- You can get a session token via `curl -XPOST -H 'Referer: http://localhost:8081' -d 'username=admin&password=admin123' http://localhost:8081/api/v2/identity/providers/basic?noRedirect=1`.
```suggestion
- You can get a session token via `curl -XPOST -H 'Referer: http://localhost:8081' -d 'username=admin&password=admin123' 'http://localhost:8081/api/v2/identity/providers/basic?noRedirect=1'`.
```

2024-03-11 20:15 UTC, ethan-haynes requested changes

2024-03-11 20:15 UTC, ethan-haynes commented on README.md
> +- You can get a session token via `curl -XPOST -H 'Referer: http://localhost:8081' -d 'username=admin&password=admin123' http://localhost:8081/api/v2/identity/providers/basic?noRedirect=1`.
Might want to add single quotes around this so the url params do n't get interpreted as variables or commands (depending on the shell where it is executed).

2024-03-12 20:03 UTC, ethan-haynes approved these changes

2024-03-13 15:25 UTC, Forfold approved these changes

2024-03-13 19:19 UTC, merged