util/sqlutil: fix handling of block delimiters in SplitQuery
target/goalert pull request #3775
Opened 2024-03-26 15:40 UTC by mastercactapus

**Description:**
The `SplitQuery` function wrongly assumed `$$` was the only possible block delimiter, when it can be a user-defined tag like `$foobar$`

This PR fixes the bug and adds a test case for the more complex case.

More info:
https://www.postgresql.org/docs/16/sql-syntax-lexical.html#SQL-SYNTAX-DOLLAR-QUOTING

2024-03-26 15:51 UTC, ethan-haynes requested changes

2024-03-26 15:51 UTC, ethan-haynes commented on util/sqlutil/splitquery.go
> +		return sqlSplitBlock(data[idx[0]:idx[1]], idx[0], data, atEOF)
we should probably have variable names that are more self-explanatory. Or comments that explain why we are doing this slice operation in place.

2024-03-26 17:32 UTC, ethan-haynes approved these changes

2024-03-27 14:27 UTC, allending313 approved these changes

2024-03-27 20:14 UTC, merged