ui/profile: always use Dest API
target/goalert pull request #3875
Opened 2024-05-15 16:41 UTC by mastercactapus

**Description:**
Updates user profile page to always to use the new dest API.
- contact method & notification rule tests superseded by playwright tests

**Which issue(s) this PR fixes:**
Part of #2639 

**Describe any introduced user-facing changes:**
The new destination form will be used

**Describe any introduced API changes:**
N/A

2024-05-15 20:53 UTC, Forfold requested changes

2024-05-15 20:53 UTC, Forfold commented on test/integration/first-login.spec.ts
> +  await expect(page.locator('[role=dialog]')).not.toBeVisible()
we should also probably check that it was deleted from the list

2024-05-15 20:53 UTC, Forfold commented on test/integration/first-login.spec.ts
> +  // ensure dialog is  not shown
```suggestion
  // ensure dialog is not shown
```

2024-05-15 21:17 UTC, Forfold approved these changes

2024-05-16 15:08 UTC, Forfold approved these changes

2024-05-16 17:43 UTC, allending313 approved these changes

2024-05-16 20:15 UTC, merged