Add default action edit and rule management dialogs
target/goalert pull request #3946
Opened 2024-06-27 19:10 UTC by mastercactapus

**Description:**
Adds action dialog, rule form, and remove dialog from the `uik-editor` branch

2024-06-27 19:44 UTC, Forfold requested changes

2024-06-27 19:44 UTC, Forfold commented on web/src/app/services/UniversalKey/DefaultActionEditDialog.tsx
> +  const [m, commit] = useMutation(mutation)
nit, for clarity:

name `m` something such as `status`, or destructure them inplace, e.g. `const [{ data, fetching, error }, commit]`

2024-06-27 19:44 UTC, Forfold commented on web/src/app/services/UniversalKey/DefaultActionEditDialog.tsx
> +  )
nit, for cleanup:

this can be put directly in the JSX, as there is no conditionals affecting how it renders

2024-06-27 19:44 UTC, Forfold commented on web/src/app/services/UniversalKey/DefaultActionEditDialog.tsx
> +  }
nit, for clarity:

```suggestion

  function handleChipClick(action: ActionInput): void {
    setEditAction(action.dest.type)
  }
  
```

2024-06-27 19:44 UTC, Forfold commented on web/src/app/services/UniversalKey/DefaultActionEditDialog.tsx
> +        })
```suggestion
        ).then((res) => {
          if (!res.error) props.onClose()
        })
```

2024-06-27 19:44 UTC, Forfold commented on web/src/app/services/UniversalKey/UniversalKeyDefaultActions.tsx
> +  const [q] = useQuery<{ integrationKey: IntegrationKey }>({
nit, for clarity:

name `q` something such as status, or destructure them inplace, e.g. const [{ data, fetching, error }, commit]

2024-06-27 19:44 UTC, Forfold commented on web/src/app/services/UniversalKey/UniversalKeyDefaultActions.tsx
> +          emptyMessage=''
```suggestion
          emptyMessage='No default action'
```

2024-06-27 19:44 UTC, Forfold commented on web/src/app/services/UniversalKey/UniversalKeyDefaultActions.tsx
> +                />
It looks like this renders a bunch of grid items inside. Is FlatList the correct parent component for this? It is only rendering the one Grid container, with chips inside.

2024-06-27 19:55 UTC, Forfold commented on web/src/app/services/UniversalKey/UniversalKeyRuleRemoveDialog.tsx
> +        })
```suggestion
        ).then((res) => {
          if (!res.error) props.onClose()
        })
```

2024-06-28 15:59 UTC, Forfold commented on web/src/app/services/UniversalKey/UniversalKeyRuleRemoveDialog.tsx
> +      errors={nonFieldErrors(removeStatus.error)}
```suggestion
  const [deleteRuleResult, commit] = useMutation(mutation)

  return (
    <FormDialog
      title='Are you sure?'
      confirm
      onClose={props.onClose}
      onSubmit={() =>
        commit(
          {
            input: {
              keyID: props.keyID,
              deleteRule: props.ruleID,
            },
          },
          { additionalTypenames: ['KeyConfig'] },
        ).then((res) => {
          if (!res.error) props.onClose()
        })
      }
      errors={nonFieldErrors(deleteRuleResult.error)}
```

2024-06-28 15:59 UTC, Forfold approved these changes

2024-06-28 17:01 UTC, allending313 approved these changes

2024-06-28 18:19 UTC, merged