engine: migrate status update manager to job queue
target/goalert pull request #4164
Opened 2024-11-26 17:24 UTC by mastercactapus

**Description:**
Migrates status updates to use the job queuing system.

Previously, the status manager would run maintenance operations every tick, followed by each subscription in a tight loop (up to 100 per tick) keeping a slice of IDs to omit (which was passed to the DB for each call).

The new approach:
- hourly periodic job to trim old subscriptions
- every 5 seconds a look-for-work periodic job that schedules jobs for individual subscriptions
- each subscription runs in it's own job in the queue, up to 5 concurrently (management tasks take priority)

**Out of Scope:**
- Adding a trigger from the CreateOrUpdate method of alerts to immediately schedule things like status updates
- With the above ^ we could update the "look for work" job to run once per minute instead

**Describe any introduced user-facing changes:**
N/A

**Describe any introduced API changes:**
N/A

2024-11-27 20:46 UTC, AlaricWhitney requested changes

2024-11-27 20:46 UTC, AlaricWhitney commented on engine/statusmgr/cleanup.go
> +func (db *DB) cleanup(ctx context.Context, j *river.Job[CleanupArgs]) error {
add functional comment to explain the purpose of the function

2024-11-27 20:46 UTC, AlaricWhitney commented on app/initriver.go
> +func (i *ignoreCancel) Handle(ctx context.Context, rec slog.Record) error {
add functional comment to explain the purpose of the function

2024-11-27 20:46 UTC, AlaricWhitney commented on engine/statusmgr/lookforwork.go
> +func (db *DB) lookForWork(ctx context.Context, j *river.Job[LookForWorkArgs]) error {
add functional comment to explain the purpose of the function

2024-11-27 20:46 UTC, AlaricWhitney commented on engine/statusmgr/setup.go
> +func (db *DB) Setup(ctx context.Context, args processinglock.SetupArgs) error {
add functional comment to explain the purpose of the function

2024-11-29 18:24 UTC, AlaricWhitney approved these changes

2024-12-03 16:08 UTC, AlaricWhitney approved these changes

2024-12-04 18:51 UTC, KatieMSB submitted a review, later dismissed

2024-12-09 20:20 UTC, AlaricWhitney approved these changes

2024-12-10 16:52 UTC, ethan-haynes approved these changes

2024-12-10 16:53 UTC, merged