Issue 895: allow searching for users by phone number
target/goalert pull request #927
Opened 2020-10-08 17:17 UTC by Quynhd07

- [x] Identified the issue which this PR solves.
- [x] Read the [**CONTRIBUTING**](https://github.com/target/goalert/blob/master/CONTRIBUTING.md) document.
- [x] Code builds clean without any errors or warnings.
- [x] Added appropriate tests for any new functionality.
- [x] All new and existing tests passed.
- [x] Added comments in the code, where necessary.
- [x] Ran `make check` to catch common errors. Fixed any that came up.

**Description:**

This PR allows for user search by phone number via filter drop down and search text field

2020-10-09 14:49 UTC, mastercactapus requested changes

2020-10-09 14:49 UTC, mastercactapus commented on web/src/app/lists/QueryList.tsx
> +  mapVariables?: (vars: any) => any
Need to add the correct type (`OperationVariables`) and add a comment for what this prop does.

2020-10-09 14:49 UTC, mastercactapus commented on web/src/app/users/UserPhoneNumberFilterContainer.js
> +UserPhoneNumberFilterContainer.propTypes = {
Since this is net-new let's make it tsx and use typescript types instead of propTypes

2020-10-15 17:24 UTC, mastercactapus requested changes
Can we get a quick cypress test for the happy path on this?

2020-10-15 17:24 UTC, mastercactapus commented on web/src/app/users/UserPhoneNumberFilterContainer.tsx
> +  const searchParam = String(useSelector(searchSelector))
`searchSelector` always returns a string (default is `''`) so there's no need to cast, however, the types in `url.ts` are a bit ambiguous currently (should probably fix that) so we can just indicate the type for now
```
  const searchParam = useSelector(searchSelector) as string
```

However, a better option would be to use the hook for params directly:
```suggestion
  const [searchParam, setSearchParam] = useURLParam('search', '')
```

2020-10-15 17:25 UTC, arurao submitted a review, later dismissed
LGTM

2020-12-17 19:21 UTC, mastercactapus commented
I think this is okay without a verification server or fuzzy searching for initial implementation -- that can be subsequent work if there's interest.

If we can get the happy path tested with existing testing tools, conflicts resolved, and comments addressed it should be good to merge.

2021-01-08 22:26 UTC, mastercactapus approved these changes

2021-02-02 15:45 UTC, mastercactapus approved these changes

2021-02-02 15:52 UTC, arurao approved these changes

2021-02-02 18:15 UTC, merged