ui: bump typescript and eslint packages
target/goalert pull request #952
Opened 2020-10-19 15:42 UTC by dctalbot

- [x] Identified the issue which this PR solves.
- [x] Read the [**CONTRIBUTING**](https://github.com/target/goalert/blob/master/CONTRIBUTING.md) document.
- [x] Code builds clean without any errors or warnings.
- [x] Added appropriate tests for any new functionality.
- [x] All new and existing tests passed.
- [x] Added comments in the code, where necessary.
- [x] Ran `make check` to catch common errors. Fixed any that came up.

**Description:**
- bump typescript to v4
- bump all eslint packages

**Which issue(s) this PR fixes:**
closes #924

2020-11-09 19:48 UTC, Forfold requested changes

2020-11-09 19:48 UTC, Forfold commented on web/src/.eslintrc.js
> +    'no-use-before-define': 'off',
I believe we left this rule on explicitly to enforce code consistency between any contributors

2020-11-09 19:58 UTC, Forfold commented on web/src/.eslintrc.js
> +    'no-use-before-define': 'off',
Ah interesting, I didn't know that so thanks for the docs link 👍

2020-11-10 16:30 UTC, Forfold approved these changes

2020-11-10 17:41 UTC, mastercactapus approved these changes

2020-11-10 17:44 UTC, merged