fixshow selected option in dropdown
target/goalert pull request #995
Opened 2020-11-05 17:50 UTC by dctalbot

- [x] Identified the issue which this PR solves.
- [ ] Read the [**CONTRIBUTING**](https://github.com/target/goalert/blob/master/CONTRIBUTING.md) document.
- [ ] Code builds clean without any errors or warnings.
- [ ] Added appropriate tests for any new functionality.
- [ ] All new and existing tests passed.
- [ ] Added comments in the code, where necessary.
- [ ] Ran `make check` to catch common errors. Fixed any that came up.

**Description:**
Please include a description of the proposed changes.
This should include details if the user experience is impacted.

**Which issue(s) this PR fixes:**
For significant amounts of work, it is best to start an issue first, preferably before the work is started.
For large pull requests, be sure to reference the associated GitHub issue(s).

Usage: `Fixes #<issue number>`, or `Fixes (paste link of issue)`.

**Out of Scope:**
Include any out of scope items here.

**Screenshots:**
If applicable, add some screenshots here.

**Describe any introduced user-facing changes:**
If introducing any user-facing changes, provide a clear description of them.

**Describe any introduced API changes:**
If introducing any API changes, provide a clear description of them.

**Additional Info:**
Any additional information or context.

2020-11-05 18:26 UTC, KatieMSB requested changes
Should probably add new Cypress tests as mentioned in #958.

2020-11-05 20:12 UTC, KatieMSB submitted a review, later dismissed

2020-11-05 22:19 UTC, mastercactapus requested changes

2020-11-05 22:19 UTC, mastercactapus commented on web/src/cypress/integration/materialSelect.ts
> +    it.only('should show selected value as an option in single-select mode', () => {
```suggestion
    it('should show selected value as an option in single-select mode', () => {
```

2020-11-05 22:19 UTC, mastercactapus commented on web/src/app/selection/MaterialSelect.tsx
> +    options.every((opt) => opt.value !== value.value)
Should we be doing this check for the array form too?

2020-11-06 16:18 UTC, mastercactapus commented on web/src/app/selection/MaterialSelect.tsx
> +    options.every((opt) => opt.value !== value.value)
Ty for the clarification!

2020-11-06 16:20 UTC, mastercactapus approved these changes

2020-11-06 16:22 UTC, KatieMSB approved these changes

2020-11-06 19:56 UTC, merged